modLoader="javafml"
loaderVersion="[44,)"
license="LGPL-3"
issueTrackerURL="https://github.com/Suel-ki/FoodEffectTooltips-Forge/issues/"

[[mods]]
modId="foodeffecttooltips"
version="${version}"
displayName="Food Effect Tooltips"
displayURL="https://www.curseforge.com/minecraft/mc-mods/food-effect-tooltips-forge"
logoFile="icon.png"
credits="Thanks DaFuqs for the original work!"
authors="Suel_ki"
description='''Adds Tooltips to food that gives Status Effects when eaten.'''

[[dependencies.foodeffecttooltips]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.foodeffecttooltips]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
